
main:
	g++ -g -std=c++11 example_copystack1.cpp coctx.cpp coctx.h coctx_swap.S co_epoll.cpp co_epoll.h co_hook_sys_call.cpp co_routine.cpp co_routine.h co_routine_inner.h -ldl

clean:
	rm -rf a.out .*.swp *.gch 
